# Generated by Django 3.1.1 on 2020-09-03 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arti_title', models.CharField(max_length=200, verbose_name='Название')),
                ('arti_text', models.TextField(verbose_name='техт')),
                ('pub_date', models.DateTimeField(verbose_name='дата')),
            ],
        ),
        migrations.CreateModel(
            name='Comm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='имя')),
                ('comment_text', models.CharField(max_length=200, verbose_name='')),
                ('arti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aa.arti')),
            ],
        ),
    ]
